version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "songs-report-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7il1j0segxm9"
s3_prefix = "songs-report-api"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
